include ../mklove/Makefile.base

CC ?= cc
TEST_PROGS := ${TEST_SRCS:%.c=%.test}
XML_FILES  := ${TEST_SRCS:%.c=%.test.xml}
COV_FILES  := ${TEST_SRCS:%.c=%.gcda} ${TEST_SRCS:%.c=%.gcno}
CFLAGS += -g
CFLAGS += -fstack-protector -DFORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -Wformat
CFLAGS += -Wall -Wfloat-equal -Wpointer-arith -O0 \
	-I$(TOPDIR) -I$(TOPDIR)/src

CPPFLAGS := $(filter-out -I. -I./src,$(CPPFLAGS))

LIBS += -lcmocka

COVERAGE_CPPFLAGS = --coverage
COVERAGE_LDFLAGS = --coverage
COVERAGE_INFO = coverage.info
COVERAGE_OUTPUT_DIRECTORY = out

.PHONY = coverage
.PRECIOUS = $(TEST_PROGS)

# Profiling
#CFLAGS += -O0 -pg
#LDFLAGS += -pg

all: test

%.test: %.c %.objdeps
	$(CC) $(CFLAGS)  $(CPPFLAGS) $< `cat $(subst .c,.objdeps,$<)` -o $@ $(LDFLAGS) $(LIBS)
	CMOCKA_MESSAGE_OUTPUT=XML CMOCKA_XML_FILE=$@.xml ./$@
	# cat ./$@.xml

coverage:
	LDFLAGS="${LDFLAGS} ${COVERAGE_LDFLAGS}" CPPFLAGS="${CPPFLAGS} ${COVERAGE_CPPFLAGS}" make
	lcov --rc lcov_branch_coverage=1 --capture --directory ../ --output-file ${COVERAGE_INFO}
	genhtml --branch-coverage ${COVERAGE_INFO} --output-directory ${COVERAGE_OUTPUT_DIRECTORY}

test: $(TEST_PROGS)

clean:
	rm -f $(TEST_PROGS) $(XML_FILES) $(COV_FILES) $(COVERAGE_INFO)
	rm -rf $(COVERAGE_OUTPUT_DIRECTORY)
