include ../Makefile.config

CC ?= cc
TEST_PROGS := ${TEST_SRCS:%.c=%.test}
CFLAGS += -g
CFLAGS += -fstack-protector -DFORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -Wformat 
       -Werror=format-security -DFORTIFY_SOURCE=2
CFLAGS += -Wall -Werror -Wfloat-equal -Wpointer-arith -O0 -I../ -I/opt/rb/include
LDFLAGS += -lpthread -lrt -lz -lrd

# Profiling
#CFLAGS += -O0 -pg
#LDFLAGS += -pg

all: test

%.test: %.c %.objdeps
	@(if ! $(CC) $(CFLAGS)  $(CPPFLAGS) $< `cat $(subst .c,.objdeps,$<)` -o $@ $(LDFLAGS) $(LIBS) ; then \
		echo "########################################";\
		echo "########################################";\
		echo "Test $< did not compile" ; \
		echo "########################################";\
		echo "########################################";\
		false ; \
	else \
		echo -n "Test $< "; \
		(LD_LIBRARY_PATH=../ ./$@ &> /dev/null && echo "passed") || \
			 (echo "failed";\
			  echo "########################################";\
			  echo "########################################";\
			  echo "Test $< failed";\
			  echo "########################################";\
			  echo "########################################";\
				false); \
	fi)


test: $(TEST_PROGS)

clean:
	rm -f $(TEST_PROGS)
