include ../Makefile.config

CC ?= cc
TEST_PROGS := ${TEST_SRCS:%.c=%.test}
CFLAGS += -g
CFLAGS += -fstack-protector -DFORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -Wformat
       -Werror=format-security -DFORTIFY_SOURCE=2
CFLAGS += -Wall -Werror -Wfloat-equal -Wpointer-arith -O0 -I ../src/decoder/ \
-I ../src/engine -I ../ -I ../src/listener/ -I ../src/util/ \-I/opt/rb/include
LDFLAGS += -lpthread -lrt -lz -lrd -lcmocka

# Profiling
#CFLAGS += -O0 -pg
#LDFLAGS += -pg

all: test

%.test: %.c %.objdeps
	$(CC) $(CFLAGS)  $(CPPFLAGS) $< `cat $(subst .c,.objdeps,$<)` -o $@ $(LDFLAGS) $(LIBS)


test: $(TEST_PROGS)

clean:
	rm -f $(TEST_PROGS)
